### ISSUE TITLE
Problems with multiple query parameters

### ISSUE THREAD

**Issue by sjn88** [EconomistDigitalSolutions/ramlapi#9] opened 2015-10-12 10:50 UTC
When more than one query parameter is in a raml file, the library panics, causing the host application to fail unexpectedly.

**Comment by buddhamagnet** [comment] 2015-10-12 11:05
Thanks @Seanseviltwin I think the panic was caused by a missig or empty pattern value in the RAML file, as it takes a string pointer. Looking at what we have now, I can see that we need to add support for multiple query parameters, as it only processes one right now so you'll end up only having support for the last one it finds as far as I can see. I'll try and make some time to add this, driven by tests.

**Comment by burrbd** [comment] 2015-11-10 15:56
This issue should be resolved by PR https://github.com/EconomistDigitalSolutions/ramlapi/pull/12

**Closed as completed by burrbd** 2015-11-10 15:56 UTC
